# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = net.thonyy.noeffectparticles
archives_name = noeffectparticles
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# Dependencies
fabric_loader_version = 0.19.5
neoforge_version = 26.2.0.88
modmenu_version=20.0.2